services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    ports:
      - 27017:27017
