services:
  http_server:
    image: jdkelley/simple-http-server:latest
    ports:
      - "80:8000"
    volumes:
      - ${HTTP_SERVER_VOLUME}:/serve
    networks:
      - delukesoft_network
  mongodb:
    image: 'mongo:7.0'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=${PORTFOLIO_MONGO_DB_NAME}
      - PORTFOLIO_MONGO_APP_USERNAME=${MONGO_USERNAME}
      - PORTFOLIO_MONGO_APP_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27018:27017"
    restart: unless-stopped
    volumes:
      - ./db/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - delukesoft_network
  authserver:
    image: kane16/centralauthserver-native:latest
    restart: unless-stopped
    environment:
      ACTIVE_PROFILE: ${AUTH_ACTIVE_PROFILE}
      SPRING_DATASOURCE_URL: ${AUTH_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${AUTH_SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_SPRING_DATASOURCE_PASSWORD}
      JWT_ISSUER: ${AUTH_JWT_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION_MINUTES: ${AUTH_JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
      JWT_REFRESH_TOKEN_EXPIRATION_DAYS: ${AUTH_JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
      FILE_UPLOAD_USER_PATH: ${AUTH_FILE_UPLOAD_USER_PATH}
    ports:
      - "${AUTH_SERVER_PORT}:8080"
    volumes:
      - ${AUTH_FILE_UPLOAD_HOST_PATH}:/app/data/users_batch.csv:ro
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - delukesoft_network
  auth_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    volumes:
      - auth_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - delukesoft_network
volumes:
  auth_data:
  portfolio_mongodata:
networks:
  delukesoft_network:
    driver: bridge
