spring:
  mongodb:
    uri: ${MONGO_CONNECTION_STRING}
  devtools:
    livereload:
      enabled: true
jwt:
  secret: ${JWT_SECRET}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
