web:
  url: http://localhost:9090
  login:
    url: http://localhost:8080
external:
  service:
    auth:
      url: http://localhost:8080
    back-office:
      url: http://localhost:8000
jwt:
  secret: secret
app:
  liquibase:
    change-log: classpath:db/changelog-test/db.changelog-master.xml