spring:
  cache:
    type: caffeine
    cache-names: portfolio, constraints
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterAccess=1d
  application:
    name: portfolio-service
  profiles:
    active: ${ACTIVE_PROFILE:docker}
  aop:
    proxy-target-class: true
  data:
    mongodb:
      database: portfolio
  liquibase:
    enabled: false
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
app:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  error:
    include-message: always
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true
springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true