spring:
  data:
    mongodb:
      database: ${PORTFOLIO_MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      uri: ${MONGO_CONNECTION_STRING}
  devtools:
    livereload:
      enabled: true
jwt:
  secret: ${JWT_SECRET}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true