server:
  port: 9090
auth-service:
  url: ${AUTH_URL:authserver:8080}
spring:
  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      uri: ${MONGO_CONNECTION_STRING}