web:
  url: http://localhost:9090
  login:
    url: http://localhost:8080
mongo:
  migration:
    connection-string: mongodb://localhost:27017/portfolio
auth-service:
  url: http://localhost:8080
jwt:
  secret: secret
app:
  liquibase:
    change-log: classpath:db/changelog-test/db.changelog-master.xml