spring:
  mongodb:
    uri: ${MONGO_CONNECTION_STRING}
jwt:
  secret: ${JWT_SECRET}
external:
  service:
    auth:
      url: ${AUTH_URL:http://authserver:8080}
    back-office:
      url: ${BOS_URL:http://bos:8000}
