spring:
  cache:
    type: caffeine
    cache-names: portfolio, constraints
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterAccess=1d
  http:
    converters:
      preferred-json-mapper: jackson2
  application:
    name: portfolio-service
  profiles:
    active: ${ACTIVE_PROFILE:docker}
  aop:
    proxy-target-class: true
  liquibase:
    enabled: false
  thymeleaf:
    cache: false
  web:
    error:
      include-message: always
  servlet:
    encoding:
      charset: UTF-8
      force: true
app:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
external:
  service:
    auth:
      name: auth-service
      url: ${AUTH_URL:http://localhost:8080}
    back-office:
      name: back-office
      url: ${BOS_URL:http://localhost:8000}
server:
  port: 9090
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  mongodb:
    uri: ${MONGO_CONNECTION_STRING}
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
