auth-service:
  url: ${AUTH_URL:http://localhost:8080}
spring:
  data:
    mongodb:
      database: ${MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      uri: ${MONGO_CONNECTION_STRING}
  devtools:
    livereload:
      enabled: true